# Generated by Django 2.1.7 on 2019-12-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('firstname', models.CharField(max_length=30, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='joindate')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='logindate')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False, verbose_name='doctor status')),
                ('is_patient', models.BooleanField(default=False, verbose_name='patient status')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='end time')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Neurology', 'Neurology'), ('Ear, Nose and Throat Disorders', 'Ear, Nose and Throat Disorders'), ('Diet and Nutrition', 'Diet and Nutrition'), ('Cardiology', 'Cardiology'), ('Psychology', 'Psychology')], max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DoctorDepartment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DoctorDepartment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
