# Generated by Django 2.1.7 on 2019-12-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='old',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctordepartment',
            name='department',
            field=models.CharField(choices=[('1', 'Neurology'), ('2', 'Ear, Nose and Throat Disorders'), ('3', 'Diet and Nutrition'), ('4', 'Cardiology'), ('5', 'Psychology')], max_length=100),
        ),
    ]
