# Generated by Django 2.1.7 on 2019-12-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191229_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_rate',
            field=models.IntegerField(default=0),
        ),
    ]
