# Generated by Django 2.1.7 on 2019-12-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_app_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrate',
            name='user',
        ),
    ]
