# Generated by Django 2.1.7 on 2019-12-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_doctorrate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorrate',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctordepartment',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='DoctorRate',
        ),
    ]
