# Generated by Django 2.1.7 on 2019-12-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191230_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordepartment',
            name='av_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
