# Generated by Django 2.1.7 on 2019-12-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctordepartment_av_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('av_rate', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctordepartment',
            name='av_rate',
        ),
        migrations.RemoveField(
            model_name='doctordepartment',
            name='rate',
        ),
        migrations.AddField(
            model_name='ratemodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DoctorDepartment'),
        ),
    ]
